'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let profile=OJ.load('ojakgyo.active',{code:'나의기록',grade:'1',className:''});
let records=[],currentId='',category='전체';
const key=()=>`ojakgyo.student.${profile.code}`;
const current=()=>records.find(r=>r.id===currentId);
function newActivity(){const d=new Date();const date=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;const follow=new Date(d);follow.setDate(follow.getDate()+21);const checkDate=`${follow.getFullYear()}-${String(follow.getMonth()+1).padStart(2,'0')}-${String(follow.getDate()).padStart(2,'0')}`;return {id:crypto.randomUUID(),fields:{title:'새 활동',date,checkDate,designType:profile.grade==='3'?'design3':'design2'},picks:[],updated:new Date().toISOString()};}
function persist(){const ok=OJ.save(key(),{app:'ojakgyo',version:1,profile,records});$('#saveState').textContent=ok?'기기에 저장됨 · '+new Date().toLocaleTimeString('ko-KR'):'저장 실패 · 파일로 내보내세요';updateProgress();return ok;}
function openProfile(){const stored=OJ.load(key(),null);try{records=stored?OJ.validate(stored).records:[];}catch{records=[];OJ.toast('기존 기록을 읽지 못했습니다. 백업 파일을 가져오세요.');}if(!records.length)records=[newActivity()];currentId=records[0].id;$('#code').value=profile.code;$('#grade').value=profile.grade;$('#className').value=profile.className;OJ.save('ojakgyo.active',profile);renderRecord();}
function renderSelect(){$('#recordSelect').innerHTML=records.map(r=>`<option value="${OJ.esc(r.id)}">${OJ.esc(r.fields.date||'날짜 없음')} · ${OJ.esc(r.fields.title||'이름 없는 활동')}</option>`).join('');$('#recordSelect').value=currentId;}
function renderRecord(){renderSelect();$$('[data-field]').forEach(el=>el.value=current().fields[el.dataset.field]||'');setDesign();renderJobs();renderPortfolio();updateProgress();}
function setDesign(){const type=current().fields.designType||'design2';$('[data-field="designType"]').value=type;['design2','design3'].forEach(t=>$(`[data-fields="${t}"]`).hidden=t!==type);}
function updateProgress(){const r=current();if(!r)return;const keys=['before','during','reason','action'];const n=keys.filter(k=>r.fields[k]?.trim()).length;$('#progress').textContent=`핵심 기록 ${n} / 4 · 누적 활동 ${records.length}개`;}
function tab(id){$$('.view').forEach(el=>el.hidden=el.id!==id);$$('[data-tab]').forEach(el=>{if(el.dataset.tab===id)el.setAttribute('aria-current','page');else el.removeAttribute('aria-current');});if(id==='portfolio')renderPortfolio();}
$('#journey').innerHTML=CAREER.stages.map((s,i)=>`<button data-go="${['today','design','mentor','next'][i]}"><b>${s[0]}</b><strong>${s[1]}</strong><small>${s[2]}</small></button>`).join('');
$$('[data-fields]').forEach(container=>{container.innerHTML=CAREER.fields[container.dataset.fields].map(([id,label,hint])=>`<label class="card"><span class="question-title">${label}</span><span class="hint">${hint}</span><textarea data-field="${id}" maxlength="12000" placeholder="나의 경험을 나의 말로 기록해요."></textarea></label>`).join('');});
$('#selfChecks').innerHTML=['오 · 흥미와 강점을 경험으로 말할 수 있다','작 · 선택한 이유를 경험의 근거로 적었다','교 · 다음에 물어볼 사람과 질문을 정했다'].map((s,i)=>`<label>${s}<select data-field="self${i}"><option value="">선택하세요</option><option>그렇다</option><option>조금</option><option>아직</option></select></label>`).join('');
function renderJobs(){const q=$('#search').value.trim().toLowerCase();const jobs=CAREER.jobs.filter(j=>(category==='전체'||j[2]===category)&&j.join(' ').toLowerCase().includes(q));$('#jobGrid').innerHTML=jobs.map(j=>{const picked=current().picks.includes(j[0]);const index=CAREER.jobs.indexOf(j);return `<article class="jobcard"><div class="jobart" style="--h:${[145,280,195,28,250,32,15,40,320,165][index]}">${j[3]}</div><small>${j[2]} / ${String(index+1).padStart(2,'0')}</small><h3>${j[1]}</h3><p>${j[5]}</p><div class="actions"><button class="btn ghost" data-detail="${j[0]}">살펴보기 ↗</button><button class="btn ${picked?'primary':''}" data-pick="${j[0]}" aria-pressed="${picked}">${picked?'✓ 관심':'＋ 관심'}</button></div></article>`;}).join('')||'<p class="empty">검색 결과가 없습니다. 다른 낱말을 입력해 보세요.</p>';$('#pickedCount').textContent=`${current().picks.length} / 2 관심 분야`;$('#selectedJobs').textContent=current().picks.length?'만나고 싶은 분야: '+current().picks.map(id=>CAREER.jobs.find(j=>j[0]===id)[1]).join(' · '):'분야 둘러보기에서 관심 있는 두 분야를 먼저 선택해 보세요.';}
$('#filters').innerHTML=['전체',...new Set(CAREER.jobs.map(j=>j[2]))].map(c=>`<button class="${c==='전체'?'active':''}" data-category="${c}" aria-pressed="${c==='전체'}">${c}</button>`).join('');
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab)tab(b.dataset.tab);if(b.dataset.go){tab(b.dataset.go);$('.workspace-tabs').scrollIntoView({behavior:'smooth'});}if(b.dataset.category){category=b.dataset.category;$$('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});renderJobs();}if(b.dataset.pick){const r=current(),id=b.dataset.pick;if(r.picks.includes(id))r.picks=r.picks.filter(x=>x!==id);else if(r.picks.length<2)r.picks.push(id);else return OJ.toast('두 분야까지 선택할 수 있어요. 기존 선택을 해제한 뒤 담아 주세요.');r.updated=new Date().toISOString();persist();renderJobs();}if(b.dataset.detail){const j=CAREER.jobs.find(j=>j[0]===b.dataset.detail);$('#jobDetail').innerHTML=`<p class="eyebrow">${j[2]} / CAREER CARD</p><h2>${j[1]}</h2><p>${j[4]}</p><h3>만나 볼 역량</h3><p>${j[5]}</p><div class="notice"><b>이런 질문은 어때요?</b><p>${j[6]}</p></div><p class="muted">질문은 수업용 예시입니다. 자신의 경험과 연결해 바꿔 보세요.</p>`;$('#jobDialog').showModal();}});
$('#closeDialog').onclick=()=>$('#jobDialog').close();$('#search').oninput=renderJobs;
$$('[data-field]').forEach(el=>el.addEventListener('input',()=>{current().fields[el.dataset.field]=el.value;current().updated=new Date().toISOString();if(el.dataset.field==='date'&&!current().fields.checkDate&&el.value){const d=new Date(el.value+'T12:00:00');d.setDate(d.getDate()+21);const v=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;current().fields.checkDate=v;$('[data-field="checkDate"]').value=v;}persist();if(el.dataset.field==='title'||el.dataset.field==='date')renderSelect();if(el.dataset.field==='designType')setDesign();}));
$('#start').onclick=()=>{tab('today');$('.workspace-tabs').scrollIntoView({behavior:'smooth'});};
$('#applyProfile').onclick=()=>{const code=$('#code').value.trim();if(!/^[가-힣a-zA-Z0-9_-]{1,32}$/.test(code))return OJ.toast('코드는 한글·영문·숫자·밑줄·하이픈으로 1~32자 입력하세요.');persist();profile={code,grade:$('#grade').value,className:$('#className').value.trim()};openProfile();persist();OJ.toast('선택한 코드의 기록을 열었습니다.');};
$('#recordSelect').onchange=e=>{currentId=e.target.value;renderRecord();};
$('#newRecord').onclick=()=>{if(records.length>=300)return OJ.toast('활동은 코드마다 최대 300개입니다.');const r=newActivity();records.unshift(r);currentId=r.id;persist();renderRecord();tab('today');};
$('#deleteRecord').onclick=()=>{if(!confirm('현재 활동을 이 기기에서 삭제할까요? 내보낸 파일은 남습니다.'))return;records=records.filter(r=>r.id!==currentId);if(!records.length)records=[newActivity()];currentId=records[0].id;persist();renderRecord();};
function renderPortfolio(){$('#portfolioContent').innerHTML=`<p>${OJ.esc(profile.code)} · ${OJ.esc(profile.grade)}학년 ${OJ.esc(profile.className)} · 활동 ${records.length}개</p>`+records.map(OJ.recordHTML).join('');}
$('#export').onclick=()=>{persist();OJ.download(`ojakgyo-${profile.code}.json`,{app:'ojakgyo',version:1,profile,records});OJ.toast('파일을 내려받았습니다. 선생님이 지정한 경로로 제출하세요.');};
$('#import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;const pack=await OJ.readFile(file);if(!confirm(`${pack.profile.code}의 활동 ${pack.records.length}개를 가져올까요? 같은 코드의 기존 기록은 이 파일로 교체됩니다.`))return;if(!OJ.save(`ojakgyo.student.${pack.profile.code}`,pack))return;profile=pack.profile;openProfile();OJ.toast('기록을 가져왔습니다.');}catch(err){OJ.toast('가져오기 실패: '+err.message);}finally{e.target.value='';}};
$('#clear').onclick=()=>{if(!confirm('내보내기를 마쳤나요? 현재 코드의 모든 기기 기록을 삭제합니다.'))return;try{localStorage.removeItem(key());localStorage.removeItem('ojakgyo.active');location.reload();}catch{OJ.toast('삭제하지 못했습니다. 브라우저 저장 설정을 확인하세요.');}};
$('#print').onclick=()=>{renderPortfolio();window.print();};
openProfile();
