'use strict';
const $=s=>document.querySelector(s);
let db=OJ.load('ojakgyo.teacher',{packs:[],notes:{}}),selected=null;
if(!db||!Array.isArray(db.packs)||!db.notes)db={packs:[],notes:{}};
const noteKey=(p,r)=>JSON.stringify([p.profile.code,r.id]);
function save(){return OJ.save('ojakgyo.teacher',db);}
function all(){return db.packs.flatMap(p=>p.records.map(r=>({p,r})));}
function render(){const items=all();$('#stats').innerHTML=[['학생',db.packs.length],['활동 기록',items.length],['실행 완료',items.filter(x=>x.r.fields.status==='해 보았다').length],['아직 못 했다',items.filter(x=>x.r.fields.status==='아직 못 했다').length]].map(([l,v])=>`<div class="stat"><span>${l}</span><b>${v}</b></div>`).join('');const grade=$('#gradeFilter').value,status=$('#statusFilter').value,q=$('#query').value.trim().toLowerCase();const visible=items.filter(({p,r})=>(!grade||p.profile.grade===grade)&&(!status||(status==='pending'?!r.fields.status:r.fields.status===status))&&[p.profile.code,p.profile.className,r.fields.title].join(' ').toLowerCase().includes(q));$('#rows').innerHTML=visible.map(({p,r})=>`<tr><td>${OJ.esc(p.profile.code)}</td><td>${OJ.esc(p.profile.grade)}학년 ${OJ.esc(p.profile.className)}</td><td>${OJ.esc(r.fields.title||'이름 없는 활동')}</td><td>${OJ.esc(r.fields.checkDate||'미지정')}</td><td>${OJ.esc(r.fields.status||'점검 전')}</td><td><button class="btn" data-open="${OJ.esc(noteKey(p,r))}">기록 보기</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">표시할 기록이 없습니다. 학생이 내보낸 JSON 파일을 가져오세요.</td></tr>';}
$('#files').onchange=async e=>{let count=0,errors=[];for(const file of e.target.files){try{const pack=await OJ.readFile(file);const old=db.packs.find(p=>p.profile.code===pack.profile.code);if(old){if(!confirm(`${pack.profile.code}의 기존 활동과 합칩니다. 같은 활동 ID는 가져온 파일로 갱신할까요?`))continue;const ids=new Set(pack.records.map(r=>r.id));pack.records=[...pack.records,...old.records.filter(r=>!ids.has(r.id))];if(pack.records.length>300)throw Error('합친 활동이 300개를 넘습니다.');db.packs=db.packs.filter(p=>p!==old);}db.packs.push(pack);count++;}catch(err){errors.push(file.name+': '+err.message);}}const ok=save();selected=null;$('#detail').innerHTML='';render();OJ.toast(`${count}개 파일 반영${ok?'':' (기기 저장 실패)'}${errors.length?' · 실패 '+errors.length+'개':''}`);if(errors.length)alert(errors.join('\n'));e.target.value='';};
['gradeFilter','statusFilter','query'].forEach(id=>$('#'+id).addEventListener('input',render));
$('#rows').onclick=e=>{const b=e.target.closest('[data-open]');if(!b)return;selected=all().find(({p,r})=>noteKey(p,r)===b.dataset.open);showDetail();};
function showDetail(){if(!selected)return;const {p,r}=selected,n=db.notes[noteKey(p,r)]||{};$('#detail').innerHTML=`<h2>${OJ.esc(p.profile.code)}의 기록</h2>${OJ.recordHTML(r)}<div class="card"><h3>교사 확인과 상담 연결</h3><label>피드백 · 연결할 사람과 자료<textarea id="feedback" maxlength="12000">${OJ.esc(n.text||'')}</textarea></label><div class="formgrid"><label>상담 연결<select id="counsel"><option value="">미확인</option><option value="필요">필요</option><option value="불필요">불필요</option></select></label><label>다음 확인일<input type="date" id="followDate" value="${OJ.esc(n.date||'')}"></label></div><p class="muted">피드백은 교사 기기에만 저장됩니다. 아래 파일을 내려받아 학생에게 별도로 전달하세요.</p><button class="btn primary" id="saveFeedback">피드백 저장</button> <button class="btn" id="downloadFeedback">피드백 파일</button></div>`;$('#counsel').value=n.counsel||'';const capture=()=>{const note={text:$('#feedback').value,counsel:$('#counsel').value,date:$('#followDate').value};db.notes[noteKey(p,r)]=note;return note;};$('#saveFeedback').onclick=()=>{capture();if(save())OJ.toast('피드백을 기기에 저장했습니다.');};$('#downloadFeedback').onclick=()=>{const note=capture();save();OJ.download(`feedback-${p.profile.code}.txt`,`${p.profile.code} · ${r.fields.title||'활동'}\n\n${note.text}\n\n상담 연결: ${note.counsel||'미확인'}\n다음 확인일: ${note.date||'미지정'}`,'text/plain;charset=utf-8');};$('#detail').scrollIntoView({behavior:'smooth'});}
$('#csv').onclick=()=>{const safe=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const rows=[['학생 코드','학년','반','활동명','활동일','실행 정도','확인일','상담 연결'],...all().map(({p,r})=>[p.profile.code,p.profile.grade,p.profile.className,r.fields.title,r.fields.date,r.fields.status,r.fields.checkDate,db.notes[noteKey(p,r)]?.counsel])];OJ.download('ojakgyo-summary.csv','\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n'),'text/csv;charset=utf-8');};
$('#backup').onclick=()=>OJ.download('ojakgyo-teacher-backup.json',{app:'ojakgyo-teacher',version:1,...db});
$('#restore').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>30*1024*1024)throw Error('30MB 이하 파일만 가능합니다.');const x=JSON.parse(await f.text());if(x.app!=='ojakgyo-teacher'||x.version!==1||!Array.isArray(x.packs)||!x.notes||typeof x.notes!=='object'||Array.isArray(x.notes))throw Error('교사 백업 파일이 아닙니다.');const packs=x.packs.map(OJ.validate);if(new Set(packs.map(p=>p.profile.code)).size!==packs.length)throw Error('학생 코드가 중복됩니다.');const notes={};for(const [k,n] of Object.entries(x.notes)){if(!n||typeof n.text!=='string'||n.text.length>12000||!['','필요','불필요'].includes(n.counsel)||typeof n.date!=='string'||n.date.length>10)throw Error('피드백 형식 오류');if(k==='__proto__'||k==='constructor')throw Error('잘못된 키');notes[k]={text:n.text,counsel:n.counsel,date:n.date};}if(!confirm('현재 교사 자료실을 백업 내용으로 교체할까요?'))return;db={packs,notes};save();$('#detail').innerHTML='';selected=null;render();OJ.toast('백업을 복원했습니다.');}catch(err){OJ.toast('복원 실패: '+err.message);}finally{e.target.value='';}};
$('#clearTeacher').onclick=()=>{if(confirm('교사 자료와 피드백을 이 기기에서 모두 삭제할까요? 먼저 백업하세요.')){db={packs:[],notes:{}};save();$('#detail').innerHTML='';selected=null;render();}};render();
